/**
 * Tippspiel
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LoginData {
    LOGIN?: boolean;
    TOKEN?: string;
    USER_ID?: number;
    NICK?: string;
    VORNAME?: string;
    NAME?: string;
    ERROR_CODE?: string;
    EMAIL?: string;
    PW?: string;
}
