/**
 * Tippspiel
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Team {
    MANNSCHAFT_ID?: number;
    NAME?: string;
    ICON?: string;
    tEAMCOLOR1?: string;
    tEAMCOLOR2?: string;
    FIFA_RANG?: number;
    ANZAHL_SIEGE?: number;
    ANZAHL_NIEDERLAGEN?: number;
    ANZAHL_UNENTSCHIEDEN?: number;
    TORVERHAELTNIS?: string;
    SATZSTATUS?: string;
    ACTIVE?: number;
}
