/**
 * Tippspiel
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Tipp {
    SPIEL_ID?: number;
    BEZEICNUNG?: string;
    nAME1?: string;
    nAME2?: string;
    iCON1?: string;
    iCON2?: string;
    tORE1?: number;
    tORE2?: number;
    ANSTOSS?: Date;
    GRUPPE?: string;
    GRUPPE_ID?: number;
    ANZ_TIPP?: number;
    tIPPTORE1?: number;
    tIPPTORE2?: number;
}
