/**
 * Tippspiel
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.2
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TippResult {
    USER_ICON?: number;
    USER_ID?: number;
    GAME_ID?: string;
    NICK?: string;
    ERGEBNIS?: string;
    PUNKTE?: number;
}
