/**
 * Tippspiel
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Tipp {
    SPIEL_ID?: number;
    BEZEICHNUNG?: string;
    NAME1?: string;
    NAME2?: string;
    ICON1?: string;
    ICON2?: string;
    TORE1?: number;
    TORE2?: number;
    ANSTOSS?: Date;
    GRUPPE?: string;
    GRUPPE_ID?: number;
    ANZ_TIPP?: number;
    TIPPTORE1?: number;
    TIPPTORE2?: number;
}
