/**
 * Tippspiel
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Tipp {
    SPIEL_ID?: number;
    BEZEICNUNG?: string;
    nAME1?: string;
    nAME2?: string;
    iCON1?: string;
    iCON2?: string;
    tORE1?: number;
    tORE2?: number;
    ANSTOSS?: Date;
    GRUPPE?: string;
    GRUPPE_ID?: number;
    ANZ_TIPP?: number;
    tIPPTORE1?: number;
    tIPPTORE2?: number;
}
