export * from './game.service';
import { GameService } from './game.service';
export * from './image.service';
import { ImageService } from './image.service';
export * from './mannschaft.service';
import { MannschaftService } from './mannschaft.service';
export * from './stats.service';
import { StatsService } from './stats.service';
export * from './tipp.service';
import { TippService } from './tipp.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [GameService, ImageService, MannschaftService, StatsService, TippService, UserService];
