/**
 * Tippspiel
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { LoginData } from '../model/loginData';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserService {

    protected basePath = 'http://192.168.0.199/tippspielDB';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * User Login
     * 
     * @param email The Users Login Email.
     * @param METHOD 
     * @param passphrase 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public login(email: string, METHOD: string, passphrase: string, observe?: 'body', reportProgress?: boolean): Observable<Array<LoginData>>;
    public login(email: string, METHOD: string, passphrase: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LoginData>>>;
    public login(email: string, METHOD: string, passphrase: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LoginData>>>;
    public login(email: string, METHOD: string, passphrase: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling login.');
        }
        if (METHOD === null || METHOD === undefined) {
            throw new Error('Required parameter METHOD was null or undefined when calling login.');
        }
        if (passphrase === null || passphrase === undefined) {
            throw new Error('Required parameter passphrase was null or undefined when calling login.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded',
            'application/json'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (METHOD !== undefined) {
            formParams = formParams.append('METHOD', <any>METHOD) || formParams;
        }
        if (passphrase !== undefined) {
            formParams = formParams.append('passphrase', <any>passphrase) || formParams;
        }

        return this.httpClient.post<Array<LoginData>>(`${this.basePath}/LOGIN/${encodeURIComponent(String(email))}`,
            convertFormParamsToString ? formParams.toString() : formParams,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * User Logout
     * 
     * @param token The Users Login Email.
     * @param METHOD 
     * @param passphrase 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logout(token: string, METHOD: string, passphrase: string, observe?: 'body', reportProgress?: boolean): Observable<Array<LoginData>>;
    public logout(token: string, METHOD: string, passphrase: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LoginData>>>;
    public logout(token: string, METHOD: string, passphrase: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LoginData>>>;
    public logout(token: string, METHOD: string, passphrase: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (token === null || token === undefined) {
            throw new Error('Required parameter token was null or undefined when calling logout.');
        }
        if (METHOD === null || METHOD === undefined) {
            throw new Error('Required parameter METHOD was null or undefined when calling logout.');
        }
        if (passphrase === null || passphrase === undefined) {
            throw new Error('Required parameter passphrase was null or undefined when calling logout.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded',
            'application/json'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (METHOD !== undefined) {
            formParams = formParams.append('METHOD', <any>METHOD) || formParams;
        }
        if (passphrase !== undefined) {
            formParams = formParams.append('passphrase', <any>passphrase) || formParams;
        }

        return this.httpClient.post<Array<LoginData>>(`${this.basePath}/LOGIN/${encodeURIComponent(String(token))}/delete`,
            convertFormParamsToString ? formParams.toString() : formParams,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
